let typeAlert = document.querySelector('#typeAlert')
let alertForm = document.querySelector('#alertForm')
let thirtSelectQuizForm = document.querySelector('#thirtSelectQuizForm')
let quizForm = document.querySelector('#quizForm')
let quizLinkForm = document.querySelector('#quizLinkForm')
let thirtSelectQuizResultForm = document.querySelector('#thirtSelectQuizResultForm')
let quizResultForm = document.querySelector('#quizResultForm')
let redirectUserForm = document.querySelector('#redirectUserForm')
let htmlNotificationForm = document.querySelector('#htmlNotificationForm')

const formController = () => {
    if(typeAlert.value === 'Aviso') {
        alertForm.classList.remove('d-none')
        alertForm.classList.add('d-block')

        thirtSelectQuizForm.classList.remove('d-block')
        thirtSelectQuizForm.classList.add('d-none')
        quizForm.classList.remove('d-block')
        quizForm.classList.add('d-none')
        quizLinkForm.classList.remove('d-block')
        quizLinkForm.classList.add('d-none')
        thirtSelectQuizResultForm.classList.remove('d-block')
        thirtSelectQuizResultForm.classList.add('d-none')
        quizResultForm.classList.remove('d-block')
        quizResultForm.classList.add('d-none')
        redirectUserForm.classList.remove('d-block')
        redirectUserForm.classList.add('d-none')
        htmlNotificationForm.classList.remove('d-block')
        htmlNotificationForm.classList.add('d-none')
    }
    if(typeAlert.value === 'Disparo de quiz') {
        thirtSelectQuizForm.classList.remove('d-none')
        thirtSelectQuizForm.classList.add('d-block')
        quizForm.classList.remove('d-none')
        quizForm.classList.add('d-block')

        alertForm.classList.remove('d-block')
        alertForm.classList.add('d-none')
        quizLinkForm.classList.remove('d-block')
        quizLinkForm.classList.add('d-none')
        thirtSelectQuizResultForm.classList.remove('d-block')
        thirtSelectQuizResultForm.classList.add('d-none')
        quizResultForm.classList.remove('d-block')
        quizResultForm.classList.add('d-none')
        redirectUserForm.classList.remove('d-block')
        redirectUserForm.classList.add('d-none')
        htmlNotificationForm.classList.remove('d-block')
        htmlNotificationForm.classList.add('d-none')
    }
    if(typeAlert.value === 'Aviso com link') {
        quizLinkForm.classList.remove('d-none')
        quizLinkForm.classList.add('d-block')

        thirtSelectQuizForm.classList.remove('d-block')
        thirtSelectQuizForm.classList.add('d-none')
        quizForm.classList.remove('d-block')
        quizForm.classList.add('d-none')
        alertForm.classList.remove('d-block')
        alertForm.classList.add('d-none')
        thirtSelectQuizResultForm.classList.remove('d-block')
        thirtSelectQuizResultForm.classList.add('d-none')
        quizResultForm.classList.remove('d-block')
        quizResultForm.classList.add('d-none')
        redirectUserForm.classList.remove('d-block')
        redirectUserForm.classList.add('d-none')
        htmlNotificationForm.classList.remove('d-block')
        htmlNotificationForm.classList.add('d-none')
    }
    if(typeAlert.value === 'Disparo de resultado de quiz') {
        quizResultForm.classList.remove('d-none')
        quizResultForm.classList.add('d-block')

        thirtSelectQuizResultForm.classList.remove('d-none')
        thirtSelectQuizResultForm.classList.add('d-block')
        quizForm.classList.remove('d-block')
        quizForm.classList.add('d-none')
        alertForm.classList.remove('d-block')
        alertForm.classList.add('d-none')
        quizLinkForm.classList.remove('d-block')
        quizLinkForm.classList.add('d-none')
        thirtSelectQuizForm.classList.remove('d-block')
        thirtSelectQuizForm.classList.add('d-none')
        redirectUserForm.classList.remove('d-block')
        redirectUserForm.classList.add('d-none')
        htmlNotificationForm.classList.remove('d-block')
        htmlNotificationForm.classList.add('d-none')
    }
    if(typeAlert.value === 'Redirecionamento de usuário') {
        redirectUserForm.classList.remove('d-none')
        redirectUserForm.classList.add('d-block')

        thirtSelectQuizResultForm.classList.remove('d-block')
        thirtSelectQuizResultForm.classList.add('d-none')
        quizForm.classList.remove('d-block')
        quizForm.classList.add('d-none')
        alertForm.classList.remove('d-block')
        alertForm.classList.add('d-none')
        quizLinkForm.classList.remove('d-block')
        quizLinkForm.classList.add('d-none')
        thirtSelectQuizForm.classList.remove('d-block')
        thirtSelectQuizForm.classList.add('d-none')
        quizResultForm.classList.remove('d-block')
        quizResultForm.classList.add('d-none')
        htmlNotificationForm.classList.remove('d-block')
        htmlNotificationForm.classList.add('d-none')
    }
    if(typeAlert.value === 'Notificação HTML') {
        htmlNotificationForm.classList.remove('d-none')
        htmlNotificationForm.classList.add('d-block')

        thirtSelectQuizResultForm.classList.remove('d-block')
        thirtSelectQuizResultForm.classList.add('d-none')
        quizForm.classList.remove('d-block')
        quizForm.classList.add('d-none')
        alertForm.classList.remove('d-block')
        alertForm.classList.add('d-none')
        quizLinkForm.classList.remove('d-block')
        quizLinkForm.classList.add('d-none')
        thirtSelectQuizForm.classList.remove('d-block')
        thirtSelectQuizForm.classList.add('d-none')
        quizResultForm.classList.remove('d-block')
        quizResultForm.classList.add('d-none')
        redirectUserForm.classList.remove('d-block')
        redirectUserForm.classList.add('d-none')
    }
}